#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Alex Brandt <alunduil@gmail.com>
# SPDX-License-Identifier: MIT
#
# Regenerate Mermaid markdown views from docs/architecture/workspace.dsl.
# Source of truth is the DSL; the .md files exist so GitHub renders the
# diagrams natively in PR diffs.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)/docs/architecture"

find . -maxdepth 1 -name 'structurizr-*.mmd' -delete

docker run --rm --user "$(id -u):$(id -g)" \
    -v "$PWD:/usr/local/structurizr" \
    structurizr/structurizr export \
    -w workspace.dsl -f mermaid -o . >/dev/null

for mmd in structurizr-*.mmd; do
    view=${mmd#structurizr-}
    view=${view%.mmd}
    slug=$(echo "$view" | tr '[:upper:]' '[:lower:]')
    # REUSE-IgnoreStart
    {
        echo '<!-- SPDX-FileCopyrightText: 2026 Alex Brandt <alunduil@gmail.com> -->'
        echo '<!-- SPDX-License-Identifier: MIT -->'
        echo '<!-- markdownlint-disable MD013 -->'
        echo ''
        echo '<!-- Generated by scripts/architecture-export.sh from workspace.dsl. -->'
        echo '<!-- Edit the DSL and re-run the export; do not edit by hand. -->'
        echo ''
        echo "# ${view}"
        echo ''
        echo '```mermaid'
        cat "$mmd"
        echo '```'
    } > "$slug.md"
    # REUSE-IgnoreEnd
done

rm -f structurizr-*.mmd
